// See http://brunch.io for documentation.
module.exports.files = {
  javascripts: {
    joinTo: {
      'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
      'app.js': /^app/,
    },
  },
  stylesheets: {joinTo: 'app.css'},
};

module.exports.plugins = {
  babel: {presets: ['latest']},
  htmlPages: {
    htmlMin: {
      caseSensitive: false,
      collapseBooleanAttributes: true,
      collapseInlineTagWhitespace: false,
      collapseWhitespace: true,
      conservativeCollapse: false,
      html5: true,
      includeAutoGeneratedTags: false,
      keepClosingSlash: false,
      minifyCSS: true,
      minifyJS: true,
      preserveLineBreaks: false,
      preventAttributesEscaping: false,
      processConditionalComments: true,
      removeAttributeQuotes: true,
      removeComments: true,
      removeEmptyAttributes: true,
      removeOptionalTags: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      sortAttributes: true,
      sortClassName: true,
    },
    destination(path) {
      return path.replace(/^app[\/\\](.*)\.html$/, '$1.html');
    },
    disabled: false,
    compileAssets: true,
  },
};
