export const REASONS_TO_DEPLOY = [
  'Um caso vai de ré encontra outro caso, daí o pode ficar alegre, vai saber.',
  'Luan, o mestre cervejeito.',
  'S2 ceva. Melhor coisa que tem ahhhh que delicia.',
  'Pegar uns milho pra cremosa.',
  'Faz lá teu um parabéns por ser fodão e um troféu.',
  'Desceu como água',
  'Logar minha mão na tua cara.',
  'La veio o Luan veio, com suas frases épicas...vai lá Luan véio...dale...dale...',
  'O mais importante é aquilo que importa.',
  'Esse Magento é uma merda.',
  'Quando eu achava que tinha visto uma luz no fim do túnel, era um trem que vinha na minha direção.',
  'Ser rico é ter dinheiro.',
  'Só é doente quem vai no médico.',
  '🔥Queima que é cache.',
  'Acho que vou começar a testar as coisas antes de subir pra homologação.',
  'Daí..........',
  'Vai saber!',
  'Cachorro quente frio é cachorro frio ou cachorro quente frio?',
  'Eu sou um meme físico',
  'Blz vazava',
  'Milho de beira de estrada foi feito pra ser roubado.',
  'Comprei um chuveiro bom, paguei 30 pila.',
  'Floripa é loco.',
  'Se eu for chamado eu vou, se eu não for chamado não tem como eu ir.',
];

export const REASONS_TO_NOT_DEPLOY = [
  'Um caso vai de ré encontra outro caso, daí o pode ficar alegre, vai saber.',
  'Luan, o mestre cervejeito.',
  'S2 ceva. Melhor coisa que tem ahhhh que delicia.',
  'Pegar uns milho pra cremosa.',
  'Faz lá teu um parabéns por ser fodão e um troféu.',
  'Desceu como água',
  'Logar minha mão na tua cara.',
  'La veio o Luan veio, com suas frases épicas...vai lá Luan véio...dale...dale...',
  'O mais importante é aquilo que importa.',
  'Esse Magento é uma merda.',
  'Quando eu achava que tinha visto uma luz no fim do túnel, era um trem que vinha na minha direção.',
  'Ser rico é ter dinheiro.',
  'Só é doente quem vai no médico.',
  '🔥Queima que é cache.',
  'Acho que vou começar a testar as coisas antes de subir pra homologação.',
  'Daí..........',
  'Vai saber!',
  'Cachorro quente frio é cachorro frio ou cachorro quente frio?',
  'Eu sou um meme físico',
  'Blz vazava',
  'Milho de beira de estrada foi feito pra ser roubado.',
  'Comprei um chuveiro bom, paguei 30 pila.',
  'Floripa é loco.',
  'Se eu for chamado eu vou, se eu não for chamado não tem como eu ir.',
];

export const REASONS_FOR_FRIDAY_AFTERNOON = [
  'Um caso vai de ré encontra outro caso, daí o pode ficar alegre, vai saber.',
  'Luan, o mestre cervejeito.',
  'S2 ceva. Melhor coisa que tem ahhhh que delicia.',
  'Pegar uns milho pra cremosa.',
  'Faz lá teu um parabéns por ser fodão e um troféu.',
  'Desceu como água',
  'Logar minha mão na tua cara.',
  'La veio o Luan veio, com suas frases épicas...vai lá Luan véio...dale...dale...',
  'O mais importante é aquilo que importa.',
  'Esse Magento é uma merda.',
  'Quando eu achava que tinha visto uma luz no fim do túnel, era um trem que vinha na minha direção.',
  'Ser rico é ter dinheiro.',
  'Só é doente quem vai no médico.',
  '🔥Queima que é cache.',
  'Acho que vou começar a testar as coisas antes de subir pra homologação.',
  'Daí..........',
  'Vai saber!',
  'Cachorro quente frio é cachorro frio ou cachorro quente frio?',
  'Eu sou um meme físico',
  'Blz vazava',
  'Milho de beira de estrada foi feito pra ser roubado.',
  'Comprei um chuveiro bom, paguei 30 pila.',
  'Floripa é loco.',
  'Se eu for chamado eu vou, se eu não for chamado não tem como eu ir.',
];

export const REASONS_FOR_AFTERNOON = [
  'Um caso vai de ré encontra outro caso, daí o pode ficar alegre, vai saber.',
  'Luan, o mestre cervejeito.',
  'S2 ceva. Melhor coisa que tem ahhhh que delicia.',
  'Pegar uns milho pra cremosa.',
  'Faz lá teu um parabéns por ser fodão e um troféu.',
  'Desceu como água',
  'Logar minha mão na tua cara.',
  'La veio o Luan veio, com suas frases épicas...vai lá Luan véio...dale...dale...',
  'O mais importante é aquilo que importa.',
  'Esse Magento é uma merda.',
  'Quando eu achava que tinha visto uma luz no fim do túnel, era um trem que vinha na minha direção.',
  'Ser rico é ter dinheiro.',
  'Só é doente quem vai no médico.',
  '🔥Queima que é cache.',
  'Acho que vou começar a testar as coisas antes de subir pra homologação.',
  'Daí..........',
  'Vai saber!',
  'Cachorro quente frio é cachorro frio ou cachorro quente frio?',
  'Eu sou um meme físico',
  'Blz vazava',
  'Milho de beira de estrada foi feito pra ser roubado.',
  'Comprei um chuveiro bom, paguei 30 pila.',
  'Floripa é loco.',
  'Se eu for chamado eu vou, se eu não for chamado não tem como eu ir.',
];

export const REASONS_FOR_WEEKEND = [
  'Humor negro são piadas feitas por negros?',
  'Eu vou é beber pra caralho hoje!',
  'Pólar?',
];
